version: "3"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
  flyway:
    image: flyway/flyway:6-alpine
    command: -url=jdbc:mysql://db:3306/ -schemas=mydb -user=root -password=admin -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  api:
    image: cicadatesting/rest-api-example:local
    ports:
      - 8080:8080
    depends_on:
      - db
      - flyway
