apiVersion: v1
kind: Pod
metadata:
  name: cicada
  labels:
    run: cicada
spec:
  serviceAccountName: cicada-engine-account
  restartPolicy: Never
  containers:
    - image: jeremyaherzog/cicada-2-engine:local
      name: cicada
      env:
        - name: TASK_TYPE
          value: kube
      volumeMounts:
        - mountPath: /tests
          name: tests-volume
        - mountPath: /reports
          name: reports-volume
  volumes:
    - name: tests-volume
      persistentVolumeClaim:
        claimName: tests-pvc
    - name: reports-volume
      persistentVolumeClaim:
        claimName: reports-pvc