# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app_pb2 as app__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/app.Greeter/SayHello',
        request_serializer=app__pb2.HelloRequest.SerializeToString,
        response_deserializer=app__pb2.HelloReply.FromString,
        )
    self.SayHelloCS = channel.stream_unary(
        '/app.Greeter/SayHelloCS',
        request_serializer=app__pb2.HelloRequest.SerializeToString,
        response_deserializer=app__pb2.HelloReply.FromString,
        )
    self.SayHelloSS = channel.unary_stream(
        '/app.Greeter/SayHelloSS',
        request_serializer=app__pb2.HelloRequest.SerializeToString,
        response_deserializer=app__pb2.HelloReply.FromString,
        )
    self.SayHelloBI = channel.stream_stream(
        '/app.Greeter/SayHelloBI',
        request_serializer=app__pb2.HelloRequest.SerializeToString,
        response_deserializer=app__pb2.HelloReply.FromString,
        )
    self.SayHelloError = channel.unary_unary(
        '/app.Greeter/SayHelloError',
        request_serializer=app__pb2.HelloRequest.SerializeToString,
        response_deserializer=app__pb2.HelloReply.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloCS(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloSS(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloBI(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloError(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=app__pb2.HelloRequest.FromString,
          response_serializer=app__pb2.HelloReply.SerializeToString,
      ),
      'SayHelloCS': grpc.stream_unary_rpc_method_handler(
          servicer.SayHelloCS,
          request_deserializer=app__pb2.HelloRequest.FromString,
          response_serializer=app__pb2.HelloReply.SerializeToString,
      ),
      'SayHelloSS': grpc.unary_stream_rpc_method_handler(
          servicer.SayHelloSS,
          request_deserializer=app__pb2.HelloRequest.FromString,
          response_serializer=app__pb2.HelloReply.SerializeToString,
      ),
      'SayHelloBI': grpc.stream_stream_rpc_method_handler(
          servicer.SayHelloBI,
          request_deserializer=app__pb2.HelloRequest.FromString,
          response_serializer=app__pb2.HelloReply.SerializeToString,
      ),
      'SayHelloError': grpc.unary_unary_rpc_method_handler(
          servicer.SayHelloError,
          request_deserializer=app__pb2.HelloRequest.FromString,
          response_serializer=app__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'app.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
