version: "3"
services:
  service:
    build: .
    ports:
      - 50051:50051
  cicada:
    image: ${ENGINE_IMAGE}
    environment:
      - CONTAINER_NETWORK=grpc_server_default
      - WORKDIR=${WORKDIR}
      - GRPC_RUNNER_IMAGE=${GRPC_RUNNER_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/tests
      - ./reports:/reports
    depends_on:
      - service
