name: Integration Test Workflow
on:
  push:
    branches:
      - dev
jobs:
  test-rest-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Start services
        run: |
          cd example_services/rest_api
          make services
      - name: Run tests
        run: |
          cd example_services/rest_api
          make run
      - name: Stop and clean
        run: |
          cd example_services/rest_api
          make clean
