name: Integration Test Workflow
on:
  push:
    branches:
      - dev
jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build containers
        run: |
          make build-engine
          make build-runner RUNNER_NAME=rest-runner
          make build-runner RUNNER_NAME=sql-runner
          make build-runner RUNNER_NAME=kafka-runner
          make build-runner RUNNER_NAME=s3-runner
          make build-runner RUNNER_NAME=grpc-runner
  test-rest-api:
    runs-on: ubuntu-latest
    needs: build-containers
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Start services
        run: |
          cd example_services/rest_api
          make services
      - name: Run tests
        run: |
          cd example_services/rest_api
          make run
      - name: Stop and clean
        run: |
          cd example_services/rest_api
          make clean
  test-file-transform-service:
    runs-on: ubuntu-latest
    needs: build-containers
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Start services
        run: |
          cd example_services/file_transform_service
          make services
      - name: Run tests
        run: |
          cd example_services/file_transform_service
          make run
      - name: Stop and clean
        run: |
          cd example_services/file_transform_service
          make clean
  test-grpc-runner:
    runs-on: ubuntu-latest
    needs: build-containers
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Start services
        run: |
          cd example_services/grpc_server
          make services
      - name: Run tests
        run: |
          cd example_services/grpc_server
          make run
      - name: Stop and clean
        run: |
          cd example_services/grpc_server
          make clean
